// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/raid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_raid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float64                `protobuf:"fixed64,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_proto_raid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{1}
}

func (x *Rect) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Rect) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

type TravelState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FromRoomId    string                 `protobuf:"bytes,3,opt,name=from_room_id,json=fromRoomId,proto3" json:"from_room_id,omitempty"`
	ToRoomId      string                 `protobuf:"bytes,4,opt,name=to_room_id,json=toRoomId,proto3" json:"to_room_id,omitempty"`
	Start         *Vec2                  `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End           *Vec2                  `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	StartedAt     float64                `protobuf:"fixed64,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndsAt        float64                `protobuf:"fixed64,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TravelState) Reset() {
	*x = TravelState{}
	mi := &file_proto_raid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelState) ProtoMessage() {}

func (x *TravelState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelState.ProtoReflect.Descriptor instead.
func (*TravelState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{2}
}

func (x *TravelState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TravelState) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *TravelState) GetFromRoomId() string {
	if x != nil {
		return x.FromRoomId
	}
	return ""
}

func (x *TravelState) GetToRoomId() string {
	if x != nil {
		return x.ToRoomId
	}
	return ""
}

func (x *TravelState) GetStart() *Vec2 {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TravelState) GetEnd() *Vec2 {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *TravelState) GetStartedAt() float64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TravelState) GetEndsAt() float64 {
	if x != nil {
		return x.EndsAt
	}
	return 0
}

type EntityState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind               string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Faction            string                 `protobuf:"bytes,4,opt,name=faction,proto3" json:"faction,omitempty"`
	ClassId            string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ProfileId          string                 `protobuf:"bytes,6,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FamilyId           string                 `protobuf:"bytes,7,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	RoomId             string                 `protobuf:"bytes,8,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Position           *Vec2                  `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Velocity           *Vec2                  `protobuf:"bytes,10,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Facing             float64                `protobuf:"fixed64,11,opt,name=facing,proto3" json:"facing,omitempty"`
	Grounded           bool                   `protobuf:"varint,12,opt,name=grounded,proto3" json:"grounded,omitempty"`
	Hp                 int32                  `protobuf:"varint,13,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp              int32                  `protobuf:"varint,14,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Animation          string                 `protobuf:"bytes,15,opt,name=animation,proto3" json:"animation,omitempty"`
	AnimationStartedAt float64                `protobuf:"fixed64,16,opt,name=animation_started_at,json=animationStartedAt,proto3" json:"animation_started_at,omitempty"`
	SpriteSize         *Vec2                  `protobuf:"bytes,17,opt,name=sprite_size,json=spriteSize,proto3" json:"sprite_size,omitempty"`
	SpriteOffset       *Vec2                  `protobuf:"bytes,18,opt,name=sprite_offset,json=spriteOffset,proto3" json:"sprite_offset,omitempty"`
	Collider           *Rect                  `protobuf:"bytes,19,opt,name=collider,proto3" json:"collider,omitempty"`
	Hurtbox            *Rect                  `protobuf:"bytes,20,opt,name=hurtbox,proto3" json:"hurtbox,omitempty"`
	InteractionBox     *Rect                  `protobuf:"bytes,21,opt,name=interaction_box,json=interactionBox,proto3" json:"interaction_box,omitempty"`
	Scale              float64                `protobuf:"fixed64,22,opt,name=scale,proto3" json:"scale,omitempty"`
	Travel             *TravelState           `protobuf:"bytes,23,opt,name=travel,proto3" json:"travel,omitempty"`
	DashTimer          float64                `protobuf:"fixed64,24,opt,name=dash_timer,json=dashTimer,proto3" json:"dash_timer,omitempty"`
	DashCooldown       float64                `protobuf:"fixed64,25,opt,name=dash_cooldown,json=dashCooldown,proto3" json:"dash_cooldown,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_proto_raid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{3}
}

func (x *EntityState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityState) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EntityState) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

func (x *EntityState) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *EntityState) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *EntityState) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *EntityState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EntityState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityState) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityState) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

func (x *EntityState) GetGrounded() bool {
	if x != nil {
		return x.Grounded
	}
	return false
}

func (x *EntityState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EntityState) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *EntityState) GetAnimationStartedAt() float64 {
	if x != nil {
		return x.AnimationStartedAt
	}
	return 0
}

func (x *EntityState) GetSpriteSize() *Vec2 {
	if x != nil {
		return x.SpriteSize
	}
	return nil
}

func (x *EntityState) GetSpriteOffset() *Vec2 {
	if x != nil {
		return x.SpriteOffset
	}
	return nil
}

func (x *EntityState) GetCollider() *Rect {
	if x != nil {
		return x.Collider
	}
	return nil
}

func (x *EntityState) GetHurtbox() *Rect {
	if x != nil {
		return x.Hurtbox
	}
	return nil
}

func (x *EntityState) GetInteractionBox() *Rect {
	if x != nil {
		return x.InteractionBox
	}
	return nil
}

func (x *EntityState) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *EntityState) GetTravel() *TravelState {
	if x != nil {
		return x.Travel
	}
	return nil
}

func (x *EntityState) GetDashTimer() float64 {
	if x != nil {
		return x.DashTimer
	}
	return 0
}

func (x *EntityState) GetDashCooldown() float64 {
	if x != nil {
		return x.DashCooldown
	}
	return 0
}

type LootState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Value         int32                  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootState) Reset() {
	*x = LootState{}
	mi := &file_proto_raid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootState) ProtoMessage() {}

func (x *LootState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootState.ProtoReflect.Descriptor instead.
func (*LootState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{4}
}

func (x *LootState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LootState) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *LootState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LootState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *LootState) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ExitState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId           string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Label            string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Area             *Rect                  `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	AssignedPlayerId string                 `protobuf:"bytes,5,opt,name=assigned_player_id,json=assignedPlayerId,proto3" json:"assigned_player_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExitState) Reset() {
	*x = ExitState{}
	mi := &file_proto_raid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitState) ProtoMessage() {}

func (x *ExitState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitState.ProtoReflect.Descriptor instead.
func (*ExitState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{5}
}

func (x *ExitState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExitState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ExitState) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ExitState) GetArea() *Rect {
	if x != nil {
		return x.Area
	}
	return nil
}

func (x *ExitState) GetAssignedPlayerId() string {
	if x != nil {
		return x.AssignedPlayerId
	}
	return ""
}

type PlacedAssetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Scale         float64                `protobuf:"fixed64,5,opt,name=scale,proto3" json:"scale,omitempty"`
	DrawOffset    *Vec2                  `protobuf:"bytes,6,opt,name=draw_offset,json=drawOffset,proto3" json:"draw_offset,omitempty"`
	Layer         string                 `protobuf:"bytes,7,opt,name=layer,proto3" json:"layer,omitempty"`
	Alpha         float64                `protobuf:"fixed64,8,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Bounds        *Rect                  `protobuf:"bytes,9,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedAssetState) Reset() {
	*x = PlacedAssetState{}
	mi := &file_proto_raid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedAssetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedAssetState) ProtoMessage() {}

func (x *PlacedAssetState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedAssetState.ProtoReflect.Descriptor instead.
func (*PlacedAssetState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{6}
}

func (x *PlacedAssetState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlacedAssetState) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *PlacedAssetState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlacedAssetState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlacedAssetState) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *PlacedAssetState) GetDrawOffset() *Vec2 {
	if x != nil {
		return x.DrawOffset
	}
	return nil
}

func (x *PlacedAssetState) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *PlacedAssetState) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *PlacedAssetState) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type JumpLinkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetRoomId  string                 `protobuf:"bytes,3,opt,name=target_room_id,json=targetRoomId,proto3" json:"target_room_id,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Area          *Rect                  `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Arrival       *Vec2                  `protobuf:"bytes,6,opt,name=arrival,proto3" json:"arrival,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JumpLinkState) Reset() {
	*x = JumpLinkState{}
	mi := &file_proto_raid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JumpLinkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpLinkState) ProtoMessage() {}

func (x *JumpLinkState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpLinkState.ProtoReflect.Descriptor instead.
func (*JumpLinkState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{7}
}

func (x *JumpLinkState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JumpLinkState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JumpLinkState) GetTargetRoomId() string {
	if x != nil {
		return x.TargetRoomId
	}
	return ""
}

func (x *JumpLinkState) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *JumpLinkState) GetArea() *Rect {
	if x != nil {
		return x.Area
	}
	return nil
}

func (x *JumpLinkState) GetArrival() *Vec2 {
	if x != nil {
		return x.Arrival
	}
	return nil
}

type RoomState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Zone            string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Bounds          *Rect                  `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Solids          []*Rect                `protobuf:"bytes,5,rep,name=solids,proto3" json:"solids,omitempty"`
	OneWayPlatforms []*Rect                `protobuf:"bytes,6,rep,name=one_way_platforms,json=oneWayPlatforms,proto3" json:"one_way_platforms,omitempty"`
	Exits           []*ExitState           `protobuf:"bytes,7,rep,name=exits,proto3" json:"exits,omitempty"`
	JumpLinks       []*JumpLinkState       `protobuf:"bytes,8,rep,name=jump_links,json=jumpLinks,proto3" json:"jump_links,omitempty"`
	Assets          []*PlacedAssetState    `protobuf:"bytes,9,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	mi := &file_proto_raid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{8}
}

func (x *RoomState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomState) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *RoomState) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *RoomState) GetSolids() []*Rect {
	if x != nil {
		return x.Solids
	}
	return nil
}

func (x *RoomState) GetOneWayPlatforms() []*Rect {
	if x != nil {
		return x.OneWayPlatforms
	}
	return nil
}

func (x *RoomState) GetExits() []*ExitState {
	if x != nil {
		return x.Exits
	}
	return nil
}

func (x *RoomState) GetJumpLinks() []*JumpLinkState {
	if x != nil {
		return x.JumpLinks
	}
	return nil
}

func (x *RoomState) GetAssets() []*PlacedAssetState {
	if x != nil {
		return x.Assets
	}
	return nil
}

type RaidLayoutState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Rooms         []*RoomState           `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	PlayerSpawns  []*Vec2                `protobuf:"bytes,3,rep,name=player_spawns,json=playerSpawns,proto3" json:"player_spawns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaidLayoutState) Reset() {
	*x = RaidLayoutState{}
	mi := &file_proto_raid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaidLayoutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidLayoutState) ProtoMessage() {}

func (x *RaidLayoutState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidLayoutState.ProtoReflect.Descriptor instead.
func (*RaidLayoutState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{9}
}

func (x *RaidLayoutState) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RaidLayoutState) GetRooms() []*RoomState {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RaidLayoutState) GetPlayerSpawns() []*Vec2 {
	if x != nil {
		return x.PlayerSpawns
	}
	return nil
}

type PlayerRaidState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RoomId         string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CarriedLoot    int32                  `protobuf:"varint,5,opt,name=carried_loot,json=carriedLoot,proto3" json:"carried_loot,omitempty"`
	AssignedExitId string                 `protobuf:"bytes,6,opt,name=assigned_exit_id,json=assignedExitId,proto3" json:"assigned_exit_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerRaidState) Reset() {
	*x = PlayerRaidState{}
	mi := &file_proto_raid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRaidState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRaidState) ProtoMessage() {}

func (x *PlayerRaidState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRaidState.ProtoReflect.Descriptor instead.
func (*PlayerRaidState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerRaidState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerRaidState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerRaidState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlayerRaidState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerRaidState) GetCarriedLoot() int32 {
	if x != nil {
		return x.CarriedLoot
	}
	return 0
}

func (x *PlayerRaidState) GetAssignedExitId() string {
	if x != nil {
		return x.AssignedExitId
	}
	return ""
}

type RaidState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaidId        string                 `protobuf:"bytes,1,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	TimeRemaining float64                `protobuf:"fixed64,5,opt,name=time_remaining,json=timeRemaining,proto3" json:"time_remaining,omitempty"`
	Seed          int64                  `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"`
	LocalPlayerId string                 `protobuf:"bytes,7,opt,name=local_player_id,json=localPlayerId,proto3" json:"local_player_id,omitempty"`
	LocalStatus   string                 `protobuf:"bytes,8,opt,name=local_status,json=localStatus,proto3" json:"local_status,omitempty"`
	Players       []*PlayerRaidState     `protobuf:"bytes,9,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaidState) Reset() {
	*x = RaidState{}
	mi := &file_proto_raid_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaidState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidState) ProtoMessage() {}

func (x *RaidState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidState.ProtoReflect.Descriptor instead.
func (*RaidState) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{11}
}

func (x *RaidState) GetRaidId() string {
	if x != nil {
		return x.RaidId
	}
	return ""
}

func (x *RaidState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RaidState) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RaidState) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RaidState) GetTimeRemaining() float64 {
	if x != nil {
		return x.TimeRemaining
	}
	return 0
}

func (x *RaidState) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RaidState) GetLocalPlayerId() string {
	if x != nil {
		return x.LocalPlayerId
	}
	return ""
}

func (x *RaidState) GetLocalStatus() string {
	if x != nil {
		return x.LocalStatus
	}
	return ""
}

func (x *RaidState) GetPlayers() []*PlayerRaidState {
	if x != nil {
		return x.Players
	}
	return nil
}

type SnapshotMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerTime       float64                `protobuf:"fixed64,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Tick             uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	LocalPlayerId    string                 `protobuf:"bytes,3,opt,name=local_player_id,json=localPlayerId,proto3" json:"local_player_id,omitempty"`
	LastProcessedSeq uint32                 `protobuf:"varint,4,opt,name=last_processed_seq,json=lastProcessedSeq,proto3" json:"last_processed_seq,omitempty"`
	Layout           *RaidLayoutState       `protobuf:"bytes,5,opt,name=layout,proto3" json:"layout,omitempty"`
	Entities         []*EntityState         `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	Loot             []*LootState           `protobuf:"bytes,7,rep,name=loot,proto3" json:"loot,omitempty"`
	Raid             *RaidState             `protobuf:"bytes,8,opt,name=raid,proto3" json:"raid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotMessage) Reset() {
	*x = SnapshotMessage{}
	mi := &file_proto_raid_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMessage) ProtoMessage() {}

func (x *SnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMessage.ProtoReflect.Descriptor instead.
func (*SnapshotMessage) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotMessage) GetServerTime() float64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *SnapshotMessage) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SnapshotMessage) GetLocalPlayerId() string {
	if x != nil {
		return x.LocalPlayerId
	}
	return ""
}

func (x *SnapshotMessage) GetLastProcessedSeq() uint32 {
	if x != nil {
		return x.LastProcessedSeq
	}
	return 0
}

func (x *SnapshotMessage) GetLayout() *RaidLayoutState {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *SnapshotMessage) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SnapshotMessage) GetLoot() []*LootState {
	if x != nil {
		return x.Loot
	}
	return nil
}

func (x *SnapshotMessage) GetRaid() *RaidState {
	if x != nil {
		return x.Raid
	}
	return nil
}

type WelcomeMessage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PlayerId              string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName            string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ClassId               string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	RaidId                string                 `protobuf:"bytes,4,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	RaidName              string                 `protobuf:"bytes,5,opt,name=raid_name,json=raidName,proto3" json:"raid_name,omitempty"`
	ContentVersion        string                 `protobuf:"bytes,6,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	ServerTime            float64                `protobuf:"fixed64,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	TickRate              float64                `protobuf:"fixed64,8,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotRate          float64                `protobuf:"fixed64,9,opt,name=snapshot_rate,json=snapshotRate,proto3" json:"snapshot_rate,omitempty"`
	InterpolationBackTime float64                `protobuf:"fixed64,10,opt,name=interpolation_back_time,json=interpolationBackTime,proto3" json:"interpolation_back_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	mi := &file_proto_raid_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{13}
}

func (x *WelcomeMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WelcomeMessage) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *WelcomeMessage) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *WelcomeMessage) GetRaidId() string {
	if x != nil {
		return x.RaidId
	}
	return ""
}

func (x *WelcomeMessage) GetRaidName() string {
	if x != nil {
		return x.RaidName
	}
	return ""
}

func (x *WelcomeMessage) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *WelcomeMessage) GetServerTime() float64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *WelcomeMessage) GetTickRate() float64 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *WelcomeMessage) GetSnapshotRate() float64 {
	if x != nil {
		return x.SnapshotRate
	}
	return 0
}

func (x *WelcomeMessage) GetInterpolationBackTime() float64 {
	if x != nil {
		return x.InterpolationBackTime
	}
	return 0
}

type PongMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    float64                `protobuf:"fixed64,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	ServerTime    float64                `protobuf:"fixed64,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	mi := &file_proto_raid_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{14}
}

func (x *PongMessage) GetClientTime() float64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *PongMessage) GetServerTime() float64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Welcome       *WelcomeMessage        `protobuf:"bytes,2,opt,name=welcome,proto3" json:"welcome,omitempty"`
	Snapshot      *SnapshotMessage       `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Pong          *PongMessage           `protobuf:"bytes,4,opt,name=pong,proto3" json:"pong,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_raid_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raid_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_raid_proto_rawDescGZIP(), []int{15}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetWelcome() *WelcomeMessage {
	if x != nil {
		return x.Welcome
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *SnapshotMessage {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ServerMessage) GetPong() *PongMessage {
	if x != nil {
		return x.Pong
	}
	return nil
}

func (x *ServerMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_raid_proto protoreflect.FileDescriptor

const file_proto_raid_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raid.proto\x12\x04raid\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\">\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x01R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\"\xf6\x01\n" +
	"\vTravelState\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12 \n" +
	"\ffrom_room_id\x18\x03 \x01(\tR\n" +
	"fromRoomId\x12\x1c\n" +
	"\n" +
	"to_room_id\x18\x04 \x01(\tR\btoRoomId\x12 \n" +
	"\x05start\x18\x05 \x01(\v2\n" +
	".raid.Vec2R\x05start\x12\x1c\n" +
	"\x03end\x18\x06 \x01(\v2\n" +
	".raid.Vec2R\x03end\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x01R\tstartedAt\x12\x17\n" +
	"\aends_at\x18\b \x01(\x01R\x06endsAt\"\xb0\x06\n" +
	"\vEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\afaction\x18\x04 \x01(\tR\afaction\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x06 \x01(\tR\tprofileId\x12\x1b\n" +
	"\tfamily_id\x18\a \x01(\tR\bfamilyId\x12\x17\n" +
	"\aroom_id\x18\b \x01(\tR\x06roomId\x12&\n" +
	"\bposition\x18\t \x01(\v2\n" +
	".raid.Vec2R\bposition\x12&\n" +
	"\bvelocity\x18\n" +
	" \x01(\v2\n" +
	".raid.Vec2R\bvelocity\x12\x16\n" +
	"\x06facing\x18\v \x01(\x01R\x06facing\x12\x1a\n" +
	"\bgrounded\x18\f \x01(\bR\bgrounded\x12\x0e\n" +
	"\x02hp\x18\r \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x0e \x01(\x05R\x05maxHp\x12\x1c\n" +
	"\tanimation\x18\x0f \x01(\tR\tanimation\x120\n" +
	"\x14animation_started_at\x18\x10 \x01(\x01R\x12animationStartedAt\x12+\n" +
	"\vsprite_size\x18\x11 \x01(\v2\n" +
	".raid.Vec2R\n" +
	"spriteSize\x12/\n" +
	"\rsprite_offset\x18\x12 \x01(\v2\n" +
	".raid.Vec2R\fspriteOffset\x12&\n" +
	"\bcollider\x18\x13 \x01(\v2\n" +
	".raid.RectR\bcollider\x12$\n" +
	"\ahurtbox\x18\x14 \x01(\v2\n" +
	".raid.RectR\ahurtbox\x123\n" +
	"\x0finteraction_box\x18\x15 \x01(\v2\n" +
	".raid.RectR\x0einteractionBox\x12\x14\n" +
	"\x05scale\x18\x16 \x01(\x01R\x05scale\x12)\n" +
	"\x06travel\x18\x17 \x01(\v2\x11.raid.TravelStateR\x06travel\x12\x1d\n" +
	"\n" +
	"dash_timer\x18\x18 \x01(\x01R\tdashTimer\x12#\n" +
	"\rdash_cooldown\x18\x19 \x01(\x01R\fdashCooldown\"\x91\x01\n" +
	"\tLootState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12&\n" +
	"\bposition\x18\x04 \x01(\v2\n" +
	".raid.Vec2R\bposition\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x05R\x05value\"\x98\x01\n" +
	"\tExitState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1e\n" +
	"\x04area\x18\x04 \x01(\v2\n" +
	".raid.RectR\x04area\x12,\n" +
	"\x12assigned_player_id\x18\x05 \x01(\tR\x10assignedPlayerId\"\x95\x02\n" +
	"\x10PlacedAssetState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12&\n" +
	"\bposition\x18\x04 \x01(\v2\n" +
	".raid.Vec2R\bposition\x12\x14\n" +
	"\x05scale\x18\x05 \x01(\x01R\x05scale\x12+\n" +
	"\vdraw_offset\x18\x06 \x01(\v2\n" +
	".raid.Vec2R\n" +
	"drawOffset\x12\x14\n" +
	"\x05layer\x18\a \x01(\tR\x05layer\x12\x14\n" +
	"\x05alpha\x18\b \x01(\x01R\x05alpha\x12\"\n" +
	"\x06bounds\x18\t \x01(\v2\n" +
	".raid.RectR\x06bounds\"\xba\x01\n" +
	"\rJumpLinkState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12$\n" +
	"\x0etarget_room_id\x18\x03 \x01(\tR\ftargetRoomId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1e\n" +
	"\x04area\x18\x05 \x01(\v2\n" +
	".raid.RectR\x04area\x12$\n" +
	"\aarrival\x18\x06 \x01(\v2\n" +
	".raid.Vec2R\aarrival\"\xce\x02\n" +
	"\tRoomState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\"\n" +
	"\x06bounds\x18\x04 \x01(\v2\n" +
	".raid.RectR\x06bounds\x12\"\n" +
	"\x06solids\x18\x05 \x03(\v2\n" +
	".raid.RectR\x06solids\x126\n" +
	"\x11one_way_platforms\x18\x06 \x03(\v2\n" +
	".raid.RectR\x0foneWayPlatforms\x12%\n" +
	"\x05exits\x18\a \x03(\v2\x0f.raid.ExitStateR\x05exits\x122\n" +
	"\n" +
	"jump_links\x18\b \x03(\v2\x13.raid.JumpLinkStateR\tjumpLinks\x12.\n" +
	"\x06assets\x18\t \x03(\v2\x16.raid.PlacedAssetStateR\x06assets\"}\n" +
	"\x0fRaidLayoutState\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12%\n" +
	"\x05rooms\x18\x02 \x03(\v2\x0f.raid.RoomStateR\x05rooms\x12/\n" +
	"\rplayer_spawns\x18\x03 \x03(\v2\n" +
	".raid.Vec2R\fplayerSpawns\"\xc0\x01\n" +
	"\x0fPlayerRaidState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12!\n" +
	"\fcarried_loot\x18\x05 \x01(\x05R\vcarriedLoot\x12(\n" +
	"\x10assigned_exit_id\x18\x06 \x01(\tR\x0eassignedExitId\"\xa1\x02\n" +
	"\tRaidState\x12\x17\n" +
	"\araid_id\x18\x01 \x01(\tR\x06raidId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\x12%\n" +
	"\x0etime_remaining\x18\x05 \x01(\x01R\rtimeRemaining\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\x03R\x04seed\x12&\n" +
	"\x0flocal_player_id\x18\a \x01(\tR\rlocalPlayerId\x12!\n" +
	"\flocal_status\x18\b \x01(\tR\vlocalStatus\x12/\n" +
	"\aplayers\x18\t \x03(\v2\x15.raid.PlayerRaidStateR\aplayers\"\xc4\x02\n" +
	"\x0fSnapshotMessage\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x01R\n" +
	"serverTime\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12&\n" +
	"\x0flocal_player_id\x18\x03 \x01(\tR\rlocalPlayerId\x12,\n" +
	"\x12last_processed_seq\x18\x04 \x01(\rR\x10lastProcessedSeq\x12-\n" +
	"\x06layout\x18\x05 \x01(\v2\x15.raid.RaidLayoutStateR\x06layout\x12-\n" +
	"\bentities\x18\x06 \x03(\v2\x11.raid.EntityStateR\bentities\x12#\n" +
	"\x04loot\x18\a \x03(\v2\x0f.raid.LootStateR\x04loot\x12#\n" +
	"\x04raid\x18\b \x01(\v2\x0f.raid.RaidStateR\x04raid\"\xe3\x02\n" +
	"\x0eWelcomeMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x17\n" +
	"\araid_id\x18\x04 \x01(\tR\x06raidId\x12\x1b\n" +
	"\traid_name\x18\x05 \x01(\tR\braidName\x12'\n" +
	"\x0fcontent_version\x18\x06 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vserver_time\x18\a \x01(\x01R\n" +
	"serverTime\x12\x1b\n" +
	"\ttick_rate\x18\b \x01(\x01R\btickRate\x12#\n" +
	"\rsnapshot_rate\x18\t \x01(\x01R\fsnapshotRate\x126\n" +
	"\x17interpolation_back_time\x18\n" +
	" \x01(\x01R\x15interpolationBackTime\"O\n" +
	"\vPongMessage\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x01R\n" +
	"clientTime\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x01R\n" +
	"serverTime\"\xc3\x01\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12.\n" +
	"\awelcome\x18\x02 \x01(\v2\x14.raid.WelcomeMessageR\awelcome\x121\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x15.raid.SnapshotMessageR\bsnapshot\x12%\n" +
	"\x04pong\x18\x04 \x01(\v2\x11.raid.PongMessageR\x04pong\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB\x1bZ\x19warpedrealms/shared/pb;pbb\x06proto3"

var (
	file_proto_raid_proto_rawDescOnce sync.Once
	file_proto_raid_proto_rawDescData []byte
)

func file_proto_raid_proto_rawDescGZIP() []byte {
	file_proto_raid_proto_rawDescOnce.Do(func() {
		file_proto_raid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raid_proto_rawDesc), len(file_proto_raid_proto_rawDesc)))
	})
	return file_proto_raid_proto_rawDescData
}

var file_proto_raid_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_raid_proto_goTypes = []any{
	(*Vec2)(nil),             // 0: raid.Vec2
	(*Rect)(nil),             // 1: raid.Rect
	(*TravelState)(nil),      // 2: raid.TravelState
	(*EntityState)(nil),      // 3: raid.EntityState
	(*LootState)(nil),        // 4: raid.LootState
	(*ExitState)(nil),        // 5: raid.ExitState
	(*PlacedAssetState)(nil), // 6: raid.PlacedAssetState
	(*JumpLinkState)(nil),    // 7: raid.JumpLinkState
	(*RoomState)(nil),        // 8: raid.RoomState
	(*RaidLayoutState)(nil),  // 9: raid.RaidLayoutState
	(*PlayerRaidState)(nil),  // 10: raid.PlayerRaidState
	(*RaidState)(nil),        // 11: raid.RaidState
	(*SnapshotMessage)(nil),  // 12: raid.SnapshotMessage
	(*WelcomeMessage)(nil),   // 13: raid.WelcomeMessage
	(*PongMessage)(nil),      // 14: raid.PongMessage
	(*ServerMessage)(nil),    // 15: raid.ServerMessage
}
var file_proto_raid_proto_depIdxs = []int32{
	0,  // 0: raid.TravelState.start:type_name -> raid.Vec2
	0,  // 1: raid.TravelState.end:type_name -> raid.Vec2
	0,  // 2: raid.EntityState.position:type_name -> raid.Vec2
	0,  // 3: raid.EntityState.velocity:type_name -> raid.Vec2
	0,  // 4: raid.EntityState.sprite_size:type_name -> raid.Vec2
	0,  // 5: raid.EntityState.sprite_offset:type_name -> raid.Vec2
	1,  // 6: raid.EntityState.collider:type_name -> raid.Rect
	1,  // 7: raid.EntityState.hurtbox:type_name -> raid.Rect
	1,  // 8: raid.EntityState.interaction_box:type_name -> raid.Rect
	2,  // 9: raid.EntityState.travel:type_name -> raid.TravelState
	0,  // 10: raid.LootState.position:type_name -> raid.Vec2
	1,  // 11: raid.ExitState.area:type_name -> raid.Rect
	0,  // 12: raid.PlacedAssetState.position:type_name -> raid.Vec2
	0,  // 13: raid.PlacedAssetState.draw_offset:type_name -> raid.Vec2
	1,  // 14: raid.PlacedAssetState.bounds:type_name -> raid.Rect
	1,  // 15: raid.JumpLinkState.area:type_name -> raid.Rect
	0,  // 16: raid.JumpLinkState.arrival:type_name -> raid.Vec2
	1,  // 17: raid.RoomState.bounds:type_name -> raid.Rect
	1,  // 18: raid.RoomState.solids:type_name -> raid.Rect
	1,  // 19: raid.RoomState.one_way_platforms:type_name -> raid.Rect
	5,  // 20: raid.RoomState.exits:type_name -> raid.ExitState
	7,  // 21: raid.RoomState.jump_links:type_name -> raid.JumpLinkState
	6,  // 22: raid.RoomState.assets:type_name -> raid.PlacedAssetState
	8,  // 23: raid.RaidLayoutState.rooms:type_name -> raid.RoomState
	0,  // 24: raid.RaidLayoutState.player_spawns:type_name -> raid.Vec2
	10, // 25: raid.RaidState.players:type_name -> raid.PlayerRaidState
	9,  // 26: raid.SnapshotMessage.layout:type_name -> raid.RaidLayoutState
	3,  // 27: raid.SnapshotMessage.entities:type_name -> raid.EntityState
	4,  // 28: raid.SnapshotMessage.loot:type_name -> raid.LootState
	11, // 29: raid.SnapshotMessage.raid:type_name -> raid.RaidState
	13, // 30: raid.ServerMessage.welcome:type_name -> raid.WelcomeMessage
	12, // 31: raid.ServerMessage.snapshot:type_name -> raid.SnapshotMessage
	14, // 32: raid.ServerMessage.pong:type_name -> raid.PongMessage
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_raid_proto_init() }
func file_proto_raid_proto_init() {
	if File_proto_raid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raid_proto_rawDesc), len(file_proto_raid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_raid_proto_goTypes,
		DependencyIndexes: file_proto_raid_proto_depIdxs,
		MessageInfos:      file_proto_raid_proto_msgTypes,
	}.Build()
	File_proto_raid_proto = out.File
	file_proto_raid_proto_goTypes = nil
	file_proto_raid_proto_depIdxs = nil
}
